import { type HostScope } from './protocol.js';
export declare function supervisorHome(): string;
export declare function runtimeHome(): string;
export declare function scopeDirectory(scope: HostScope): string;
export declare function endpointFor(directory: string): string;
export declare function descriptorPath(directory: string): string;
export declare function scopePath(directory: string): string;
export declare function lockPath(directory: string): string;
export declare function leaseDirectory(directory: string): string;
export declare function runtimeSlotDirectory(scope: HostScope, runtimeVersion: string): string;
